# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20170315_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='type_partner',
            field=models.CharField(choices=[('info', 'Информационный'), ('finance', 'Финансовый'), ('general', 'Генеральный')], max_length=300, verbose_name='Тип партнера'),
        ),
    ]
