# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20170316_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес'),
        ),
    ]
