# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 19:29
from __future__ import unicode_literals

from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20170309_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Главное изображение'),
        ),
    ]
