# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 09:41
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_auto_20170309_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Статья')),
            ],
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Участника', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterModelOptions(
            name='socialnetwork',
            options={'verbose_name': 'Социальные сети', 'verbose_name_plural': 'Социальные сети'},
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Участники проекта'),
        ),
    ]
