# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_auto_20170310_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialnetwork',
            options={'verbose_name': 'социальных сетей', 'verbose_name_plural': 'социальных сетей'},
        ),
        migrations.AddField(
            model_name='project',
            name='git',
            field=models.URLField(blank=True, null=True, verbose_name='Cсылка на Git'),
        ),
    ]
