# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 13:50
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_auto_20170310_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название партнера')),
                ('type_partner', models.CharField(max_length=300, verbose_name='Тип партнера')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('address', models.CharField(max_length=500, verbose_name='Адресс')),
                ('site', models.CharField(max_length=500, verbose_name='Сайт')),
                ('phone', models.CharField(max_length=500, verbose_name='Телефон')),
                ('image', filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Главное изображение'),
        ),
    ]
