# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 16:35
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Короткое описание'),
        ),
    ]
