# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170308_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seo',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='seo',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='SEO', to='blog.SEO'),
            preserve_default=False,
        ),
    ]
