# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_auto_20170310_1905'),
        ('blog', '0003_seo_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='project_blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.Project'),
        ),
    ]
