# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20170308_1649'),
        ('blog', '0003_auto_20170308_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='seo',
        ),
        migrations.AddField(
            model_name='seo',
            name='article',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blog.Article'),
        ),
        migrations.AddField(
            model_name='seo',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='event.Event'),
        ),
    ]
