# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('start', models.DateTimeField(verbose_name='Начало')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='Открыть коменты?')),
                ('featured_image', models.ImageField(upload_to='', verbose_name='Главное изображение')),
                ('profile_image', models.ImageField(upload_to='', verbose_name='Изображение профиля')),
            ],
            options={
                'verbose_name_plural': 'Мероприятия',
                'ordering': ('-start',),
                'verbose_name': 'Мероприятие',
            },
        ),
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('name', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Местоположения',
                'verbose_name': 'Местоположение',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.EventLocation', verbose_name='Местоположение'),
        ),
    ]
