# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 16:35
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170308_1635'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internet_available', models.BooleanField(verbose_name='Есть доступ к интернету')),
                ('take_computer', models.BooleanField(verbose_name='Брать компьютер')),
                ('site', models.URLField(verbose_name='Сайт мероприятия')),
                ('value', models.CharField(max_length=300, verbose_name='Стоимость')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='Статья'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.Tag', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='event',
            name='featured_image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='event',
            name='profile_image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, null=True, verbose_name='Изображение профиля'),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='address',
            field=models.CharField(max_length=500, verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='additioninfo',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event'),
        ),
    ]
