# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additioninfo',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='internet_available',
            field=models.BooleanField(default=True, verbose_name='Есть доступ к интернету'),
        ),
        migrations.AddField(
            model_name='event',
            name='site',
            field=models.URLField(default='', verbose_name='Сайт мероприятия'),
        ),
        migrations.AddField(
            model_name='event',
            name='take_computer',
            field=models.BooleanField(default=True, verbose_name='Брать компьютер'),
        ),
        migrations.AddField(
            model_name='event',
            name='value',
            field=models.CharField(default='Бесплатно', max_length=300, verbose_name='Стоимость'),
        ),
        migrations.DeleteModel(
            name='AdditionInfo',
        ),
    ]
