# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20170310_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.BooleanField(default=False, verbose_name='Гавная новость'),
        ),
    ]
