# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='sub_title',
            field=models.CharField(default=2, max_length=500, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.BooleanField(default=False, verbose_name='Главная новость'),
        ),
    ]
