# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20170311_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='sub_title',
            field=models.CharField(max_length=500, verbose_name='Слоган'),
        ),
    ]
