# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django_ymap.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20170311_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlocation',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='address',
            field=django_ymap.fields.YmapCoord(max_length=200),
        ),
    ]
