# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django_ymap.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20170312_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlocation',
            name='title',
        ),
        migrations.AddField(
            model_name='eventlocation',
            name='point',
            field=django_ymap.fields.YmapCoord(default=1, max_length=200, verbose_name='Выберите место на карте'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventlocation',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адресс'),
        ),
    ]
